server:
  servlet:
    context-path: /card-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///${DB_DATABASE:depraga}
    username: ${DB_USERNAME:depraga}
    password: ${DB_PASSWORD:4321}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DB_CLOUD_SQL_INSTANCE:numeric-poetry-382822:us-central1:testdata}
        sslmode: disable

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
